### ISSUE TITLE
How to make left sidebar fixed?

### ISSUE THREAD

**Issue by krisnaw** [kjdion84/bsadmin#2]
Hi @kjdion84 
Thanks for making this example
It's really good, but I just wonder if it possible to make the left sidebar fixed? So only the main content can be scroll up and down.

**Comment by kjdion84** [comment]
This uses flexbox, you'd have to recode it from scratch to use fixed positioning. I personally do not like this approach because if the menu is quite long then it runs into the issue of adding an extra scrollbar to the menu itself.
