### ISSUE TITLE
Close sidebar

### ISSUE THREAD

**Issue by krosoftware** [kjdion84/bsadmin#7]
Hello
how to close sidebar once Sidebar Link is clicked - when in phone view?
Thank you.

**Comment by kjdion84** [comment]
Click the menu icon again.

**Comment by krosoftware** [comment]
Yes I know that, I mean how to close it automatically? With other words, when user click on Sidebar to execute some command, Sidebar should be closed. Thank you.

**Comment by krosoftware** [comment]
OK I found it: $('.sidebar').toggleClass('toggled');
