### ISSUE TITLE
Only one dropdown active?

### ISSUE THREAD

**Issue by krosoftware** [kjdion84/bsadmin#8]
Hello
how to have only one dropdown active? You have 2 dropdown's, Dropdown Link and Dropdown Link 2. How to keep only one opened? For Example, when Dropdown Link is opened and when I click on Dropdown Link2, it need to close previous dropdown. Thank you.

**Comment by kjdion84** [comment]
See how Bootstrap 4 handles collapsing. Basically, you would have to add some Javascript that collapses all open dropdowns when you click a new one.
